server:
  servlet:
    context-path: /api
spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:wetalk;MODE=MySQL
  jpa:
    defer-datasource-initialization: true
security:
  jwt:
    secret: changeit
    expiration-time: 864000000
    token-prefix: Bearer
    header: Authorization